### ISSUE TITLE
Cannot run application

### ISSUE THREAD

**Issue by EricHier** [alexwohlbruck/google-photos-wallpaper#35]
Hi there, 

I did just try to run the application as specified in the readme.md - but it does not work for me. After installing all the dependencies with pip I get this error: 

```
(env) C:\Users\*****\Code\google-photos-wallpaper>python3 main.py
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from src.scheduler import Scheduler
  File "C:\Users\*****\Code\google-photos-wallpaper\src\scheduler.py", line 8, in <module>
    options = Options.get_user_options()
  File "C:\Users\*****\Code\google-photos-wallpaper\src\options.py", line 43, in get_user_options
    with open(OPTIONS_PATH, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\*****\\Code\\google-photos-wallpaper\\storage/options.json'
```

Is it correct that there is no options directory? What do I miss? I really appreciate your work and hope that you can help me to get it up and running. Thank you in advance! :)

**Comment by alexwohlbruck** [comment]
Hey, it's been a minute since I have worked on this project. I would like to get it finished, but right now is not in a stable state. Looks like it's trying to read the options file but it doesn't exist. Try creating a blank options.json file in that directory and running again.

**Comment by EricHier** [comment]
@alexwohlbruck Thank you for your answer! :) I didn't get it running but I think I will wait for you to get it into a stable state. Can't wait to use it. :)

**Comment by alexwohlbruck** [comment]
Id really love to get this app fully functioning, I'll start work again as soon as i have time. Last time i was working on this i got stuck trying to make an auto-update feature. That and some bug fixes are the last thing i want to do before i make a 1.0 release.

**Comment by tarmacjupiter** [comment]
Yeah, I also had this same error when trying to install and run this application. I'm not sure if you're still updating but after making a blank options.json it threw me a JSON error. I didn't expect it to work but nonetheless thought I'd share.

**Comment by alexwohlbruck** [comment]
I made some changes in 451beb3aebae345bde9490e5278cc9f26a0888f6 that should resolve these issues. I'd like to get this project somewhat working for regular users so I'll maybe be putting some more time in.

**Comment by EricHier** [comment]
I was able to run the application although the options window was very buggy and did not finish loading the details after signing in.
